# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Signhost api documentation
email: support@signhost.com
description: > # this means to ignore newlines until "baseurl:"
  Digitally sign your documents using Signhost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://signhost.com" # the base hostname & protocol for your site
twitter_username: evidos
github_username:  evidos

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
